package com.giraffe.tudeeapp.design_system.resources

import androidx.compose.runtime.staticCompositionLocalOf

data class TudeeString(
    val appName: String,
    val taskDetails: String,
    val priorityIcon: String,
    val high: String,
    val medium: String,
    val low: String,
    val categoryIcon: String,
    val checkmarkContainer: String,
    val tudeeSliderSubtitle: String,
    val tudeeSliderTitle: String,
    val tudee: String,
    val appTagline: String,
    val taskIcon: String,
    val doneTasks: String,
    val inProgressTasks: String,
    val toDoTasks: String,
    val nothingOnYourList: String,
    val subtitleZeroProgress: String,
    val titleZeroProgress: String,
    val titleGreatWork: String,
    val subtitleGreatWork: String,
    val partiallyCompletedSubtitle: String,
    val partiallyCompletedTitle: String,
    val textValue: String,
    val hint: String,
    val calendarIcon: String,
    val negativeTextButton: String,
    val noTasks: String,
    val addYourFirstTask: String,
    val taskCardImageBackgroundDescription: String,
    val overwhelmedWithTasks: String,
    val letBringOrder: String,
    val procrastinating: String,
    val disappointed: String,
    val celebrateTogether: String,
    val celebrateProgress: String,
    val splashBackground: String,
    val skip: String,
    val splashLogo: String,
    val okButton: String,
    val cancelButton: String,
    val clearButton: String,
    val datePickerPlaceholder: String,
    val dueDateHint: String,
    val priority: String,
    val category: String,
    val inProgress: String,
    val toDo: String,
    val done: String,
    val cardOverviewIcon: String,
    val sliderSubtitleForEmptyTasks: String,
    val editTask: String,
    val add: String,
    val save: String,
    val addTask: String,
    val taskAddedSuccessfully: String,
    val taskEditedSuccessfully: String,
    val addNewCategory: String,
    val addedCategorySuccessfully: String,
    val someErrorHappened: String,
    val categories: String,
    val editCategory: String
)

val defaultStrings = TudeeString(
    appName = "Tudee App",
    taskDetails = "Task Details",
    priorityIcon = "Priority icon",
    high = "High",
    medium = "Medium",
    low = "Low",
    categoryIcon = "Category icon",
    checkmarkContainer = "Checkmark Container",
    tudeeSliderSubtitle = "You've completed 3 out of 10 \ntasks Keep going!",
    tudeeSliderTitle = "Stay working!",
    tudee = "Tudee",
    appTagline = "Your cute Helper for Every Task",
    taskIcon = "Task Icon",
    doneTasks = "Done",
    inProgressTasks = "In progress",
    toDoTasks = "To-Do",
    nothingOnYourList = "Nothing on your list …",
    subtitleZeroProgress = "You just scrolling, not working.\nTudee is watching.back to work!!!",
    titleZeroProgress = "Zero progress?!",
    titleGreatWork = "Tadaa!",
    subtitleGreatWork = "You’re doing amazing!!!\nTudee is proud of you.",
    partiallyCompletedSubtitle = "You've completed %1\$s out of %2\$s \ntasks Keep going!",
    partiallyCompletedTitle = "Stay working!",
    textValue = "hello",
    hint = "Full name",
    calendarIcon = "Calendar Icon",
    negativeTextButton = "Submit",
    noTasks = "No tasks for today!",
    addYourFirstTask = "Tap the + button to add your first one.",
    taskCardImageBackgroundDescription = "task card image background",
    overwhelmedWithTasks = "Overwhelmed with tasks?",
    letBringOrder = "Let’s bring some order to the chaos.\nTudee is here to help you sort, plan, and\nbreathe easier.",
    procrastinating = "Uh-oh! Procrastinating again",
    disappointed = "Tudee not mad… just a little\ndisappointed, Let’s get back on track\ntogether.",
    celebrateTogether = "Let’s complete tasks and celebrate\ntogether.",
    celebrateProgress = "Progress is progress.Tudee will\ncelebrate you on for every win, big or\nsmall.",
    splashBackground = "Splash Background",
    skip = "Skip",
    splashLogo = "Splash Logo",
    okButton = "OK",
    cancelButton = "Cancel",
    clearButton = "Clear",
    datePickerPlaceholder = "Select a due date",
    dueDateHint = "Due Date",
    priority = "Priority",
    category = "Category",
    inProgress = "In Progress",
    toDo = "To-Do",
    done = "Done",
    cardOverviewIcon = "card overview icon",
    sliderSubtitleForEmptyTasks = "Fill your day with something \nawesome.",
    editTask = "Edit Task",
    add = "Add",
    save = "Save",
    addTask = "Add Task",
    taskAddedSuccessfully = "Task Added Successfully",
    taskEditedSuccessfully = "Task Edited Successfully",
    addNewCategory = "Add new category",
    addedCategorySuccessfully = "Added category successfully.",
    someErrorHappened = "Some error happened",
    categories = "Categories",
    editCategory = "Edit category"
)

val arStrings = TudeeString(
    appName = "تودي",
    taskDetails = "تفاصيل المهمة",
    priorityIcon = "رمز الأولوية",
    high = "عالية",
    medium = "متوسطة",
    low = "منخفضة",
    categoryIcon = "رمز الفئة",
    checkmarkContainer = "حاوية علامة الصح",
    tudeeSliderSubtitle = "لقد أكملت 3 من أصل 10 مهام، تابع!",
    tudeeSliderTitle = "تابع العمل!",
    tudee = "تودي",
    appTagline = "مساعدك اللطيف لكل مهمة",
    taskIcon = "رمز المهمة",
    doneTasks = "منتهية",
    inProgressTasks = "قيد التنفيذ",
    toDoTasks = "للقيام بها",
    nothingOnYourList = "لا توجد مهام في قائمتك …",
    subtitleZeroProgress = "أنت فقط تتصفح، لا تعمل. تودي يراقبك، عُد للعمل!",
    titleZeroProgress = "لا تقدم؟!",
    titleGreatWork = "أحسنت!",
    subtitleGreatWork = "أنت تقوم بعمل رائع!!!\nتودي فخور بك.",
    partiallyCompletedSubtitle = "لقد أكملت %1\$s من أصل %2\$s مهمة، تابع!",
    partiallyCompletedTitle = "تابع العمل!",
    textValue = "مرحبًا",
    hint = "الاسم الكامل",
    calendarIcon = "رمز التقويم",
    negativeTextButton = "إرسال",
    noTasks = "لا توجد مهام اليوم!",
    addYourFirstTask = "اضغط على زر + لإضافة أول مهمة.",
    taskCardImageBackgroundDescription = "خلفية بطاقة المهمة",
    overwhelmedWithTasks = "تشعر بالإرهاق من المهام؟",
    letBringOrder = "دعنا ننظم الفوضى.\nتودي هنا لمساعدتك في الترتيب، التخطيط، والتنفس براحة.",
    procrastinating = "تؤجل المهام مجددًا؟",
    disappointed = "تودي غير غاضب… فقط محبط قليلًا، دعنا نعود للمسار الصحيح سويًا.",
    celebrateTogether = "لنُكمل المهام ونحتفل سويًا.",
    celebrateProgress = "كل تقدم يُحتفل به. تودي سيحتفل بك في كل إنجاز، كبير أو صغير.",
    splashBackground = "خلفية البداية",
    skip = "تخطي",
    splashLogo = "شعار البداية",
    okButton = "حسنًا",
    cancelButton = "إلغاء",
    clearButton = "مسح",
    datePickerPlaceholder = "اختر تاريخًا",
    dueDateHint = "تاريخ الاستحقاق",
    priority = "الأولوية",
    category = "الفئة",
    inProgress = "قيد التنفيذ",
    toDo = "للقيام بها",
    done = "منتهية",
    cardOverviewIcon = "رمز نظرة عامة على البطاقة",
    sliderSubtitleForEmptyTasks = "املأ يومك بشيء رائع.",
    editTask = "تعديل المهمة",
    add = "إضافة",
    save = "حفظ",
    addTask = "إضافة مهمة",
    taskAddedSuccessfully = "تمت إضافة المهمة بنجاح",
    taskEditedSuccessfully = "تم تعديل المهمة بنجاح",
    addNewCategory = "إضافة فئة جديدة",
    addedCategorySuccessfully = "تمت إضافة الفئة بنجاح.",
    someErrorHappened = "حدث خطأ ما",
    categories = "الفئات",
    editCategory = "تعديل الفئة"
)

val LocalTudeeStrings = staticCompositionLocalOf { defaultStrings }
